EXE_NAME = Stack
SRC_PATH = src
BIN_PATH = bin

INCLUDES = -I $(SRC_PATH)/

#objects = main.o stack.o
SOURCES = src/main.c src/stack.c
		
all:
	gcc -g $(INCLUDES) $(SOURCES) -o $(BIN_PATH)/$(EXE_NAME)

#clean:
	#rm $(BIN_PATH) main.o stack.o
